version: "3.9"
name: "dev-davidsilva-music"

networks:
  app-network:
    name: dev-davidsilva-music-network

volumes:
  database-data:
    name: dev-davidsilva-music-database-data

services:
  database:
    image: "postgres:17.4-bookworm"
    container_name: dev-davidsilva-music-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=music
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - app-network
